spring:
  application:
    name: weather-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/weather}
    username: ${SPRING_DATASOURCE_USERNAME:weather}
    password: ${SPRING_DATASOURCE_PASSWORD:weather}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration